version: "1.0"
info:
  model: int-scaffold
packages:
- name: CsinGitHubExternalProject
  gitServerName: csingithub
  gitUrl: https://github.com/ArtiKhareIBM
  gitUsername: ArtiKhareIBM
  gitBranch: main
