version: "1.0"
info:
  model: int-scaffold
packages:
- name: CsinGitHubExternalProject
  gitServerName: csingithub
  gitUrl: https://github.com/ArtiKhareIBM
  gitUsername: ArtiKhareIBM
  gitBranch: main
- name: substractpackage
  gitServerName: csingitlab
  gitUrl: https://gitlab.com/ArtiKhareGitlabnew
  gitUsername: ArtiKhareGitlabnew
  gitBranch: master
